/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactivelearn;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test 
    void appHasAGreeting() {
       System.out.println("Hello, world!");
    }
}
